<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  ~ $Id: surveyable.wsdl 367 2010-03-25 13:53:16Z kchristiansen $
  ~ $Revision: 367 $
  ~ $Date: 2010-03-25 14:53:16 +0100 (Thu, 25 Mar 2010) $
  ~ $Author: kchristiansen $
  ~
  ~ The DOMS project.
  ~ Copyright (C) 2007-2010  The State and University Library
  ~
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<definitions
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:tns="http://surveyable.domsutil.doms.statsbiblioteket.dk/"
        targetNamespace="http://surveyable.domsutil.doms.statsbiblioteket.dk/"
        name="SurveyableService">
    <types>
        <xsd:schema>
            <xsd:import
                    namespace="http://surveyable.domsutil.doms.statsbiblioteket.dk/"
                    schemaLocation="surveyable.xsd"/>
        </xsd:schema>
    </types>
    <message name="getStatusSince">
        <part name="parameters" element="tns:getStatusSince"/>
    </message>
    <message name="getStatusSinceResponse">
        <part name="parameters" element="tns:getStatusSinceResponse"/>
    </message>
    <message name="getStatus">
        <part name="parameters" element="tns:getStatus"/>
    </message>
    <message name="getStatusResponse">
        <part name="parameters" element="tns:getStatusResponse"/>
    </message>
    <portType name="Surveyable">
        <documentation>
Something that offers status messages for surveillance.
        </documentation>
        <operation name="getStatusSince">
            <documentation>
Get all status messages newer than the given time.
An application should use the newest timestamp in the given messages
from the last call as input to this method next time it calls it, to
ensure not losing messages.

The time is specified in seconds since 1970-01-01 00:00:00.000Z
            </documentation>
            <input message="tns:getStatusSince"/>
            <output message="tns:getStatusSinceResponse"/>
        </operation>
        <operation name="getStatus">
            <documentation>
Get all status messages
            </documentation>
            <input message="tns:getStatus"/>
            <output message="tns:getStatusResponse"/>
        </operation>
    </portType>
    <binding name="SurveyableBinding"
             type="tns:Surveyable">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"
                      style="document"/>
        <operation name="getStatusSince">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="getStatus">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="SurveyableService">
        <port name="Surveyable"
              binding="tns:SurveyableBinding">

            <soap:address
                    location="http://localhost:8080/surveyable/"/>
        </port>
    </service>
</definitions>

